# https://github.com/Candinya/Kratos-Rebirth/blob/master/_config.yml
################## 系统配置 ##################

search:
  includes:
    - post
    - page

################## 样式配置 ##################
index:
  style: card

# 图片配置
image:
  favicon: "/assets/pc-programming-icon.png" # 站点图标
  avatar: "https://gravatar.com/avatar/39d6ecc6926e02f7241c8d9225f9eb5a6491a6f13cfaf6ef261b4e44dbd6be55?s=200" # 个人信息挂件上的头像
  about: # 介绍卡片
    light: "/assets/p0528_m.png" # 亮色模式
    dark: "/assets/p0527_m.png" # 暗色模式
  banner:
    light: "/assets/Pngtree—autumn landscape train far illustration_939895.jpg"
    dark: "/assets/Pngtree—light snow landscape train illustration_967224.jpg"
  # background:
    # light: "https://dev.krt.moe/demo-assets/bg.webp"
    # dark: "https://dev.krt.moe/demo-assets/bg.webp"

# 顶部导航栏配置
nav:
  items:
    - label: 首頁
      icon: home
      url: /
    - label: 所有文章
      icon: <i class="fa-regular fa-file-zipper"></i>
      url: /archives/
    # - label: 相關連結
    #   icon: link
    #   submenu:
    #     - label: 代码仓库
    #       icon: code
    #       url: https://github.com/Candinya/Kratos-Rebirth
    #     - label: 项目文档
    #       icon: book
    #       url: https://wiki.krt.moe
    - label: 相關工具
      icon: <i class="fa-solid fa-toolbox"></i>
      url: /tools/
    - label: 關於本站
      icon: info-circle
      url: /about/
    - label: RSS
      icon: rss
      url: /atom.xml
    - label: 搜尋
      icon: search
      url: /search/
    - label: 部落格舊站
      icon: <i class="fa-solid fa-right-to-bracket"></i>
      url: https://blog-legacy.yuaner.tw

# Footer 页脚配置
footer:
  links:
    - icon: home
      link: https://yuaner.tw
    - icon: <i class="fa-brands fa-github"></i>
      link: https://github.com/chyuaner
    - icon: <i class="fa-brands fa-facebook-f"></i>
      link: https://facebook.com/chyuaner
    - icon: <svg fill="currentColor" width="800px" height="800px" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M17.203 2.542c-4.073-0.031-7.938 1.786-10.505 4.943-0.13 0.156-0.255 0.313-0.38 0.474h0.005c0.313-0.266 0.63-0.464 0.958-0.594l0.078-0.031c0.396-0.151 0.802-0.198 1.198-0.12 1.922 0.385 2.922 3.479 2.234 6.911s-2.802 5.901-4.719 5.521c-1.349-0.271-2.24-1.875-2.417-3.99v-0.010 0.073c-0.005 0.177-0.005 0.354 0 0.531v0.177c0.005 0.198 0.021 0.396 0.031 0.589 0.010 0.089 0.016 0.182 0.026 0.271 0.151 1.594 0.583 3.146 1.281 4.589 0.083 0.167 0.042 0.37-0.104 0.484l-0.37 0.302c-0.38 0.313-0.531 0.823-0.385 1.292 0 0.010 0.005 0.016 0.010 0.021 0.021 0.068 0.047 0.13 0.078 0.193l0.068-0.052 0.302-0.234c0.37-0.281 0.792 0.276 0.422 0.557l-0.323 0.245-0.052 0.036 1.568 1.932c0.427 0.516 1.182 0.594 1.703 0.177l0.344-0.281c0.146-0.12 0.354-0.12 0.5 0 2.469 1.964 5.547 2.995 8.703 2.906 2.667-0.063 5.25-0.927 7.427-2.474 0.156-0.109 0.37-0.094 0.505 0.036l0.219 0.208c0.432 0.406 1.099 0.443 1.573 0.078l-0.005-0.005-0.281-0.266c-0.313-0.318 0.141-0.797 0.479-0.505l0.297 0.276 1.682-1.766c0.458-0.484 0.438-1.25-0.047-1.708l-0.349-0.333c-0.13-0.125-0.161-0.323-0.073-0.479 1.505-2.708 2.021-5.849 1.474-8.896 0.401-0.37 1.135-1.099 1.422-1.724 0.307-0.667 0.391-1.359-0.427-1.057-0.635 0.24-1.125 0.391-1.719 0.255-1.885-4.792-6.458-8.255-11.797-8.531-0.214-0.016-0.422-0.021-0.635-0.021zM3.021 8.328c-1.198 0.021-1.964 1.276-1.443 2.354-1.094 0.042-1.844 1.125-1.49 2.161 0.349 1.036 1.599 1.448 2.495 0.818 0.234-0.167 0.406-0.385 0.526-0.625 0.25 0.453 0.615 0.833 1.036 1.099-0.005 0.266 0 0.531 0.026 0.797 0.135 1.641 0.823 2.88 1.865 3.089 1.484 0.297 3.12-1.615 3.651-4.266 0.531-2.656-0.24-5.047-1.724-5.344-0.583-0.115-1.182 0.109-1.734 0.578-0.599 0.51-1.135 1.318-1.521 2.307-0.010-0.005-0.026-0.005-0.036-0.010-0.188-0.052-0.286-0.177-0.417-0.203 0.979-1.063 0.208-2.781-1.234-2.755zM6.839 9.99c0.068 0 0.141 0.005 0.208 0.021 0.969 0.188 1.474 1.745 1.13 3.474-0.349 1.729-1.411 2.974-2.38 2.781-0.656-0.13-1.099-0.896-1.208-1.911 0.245 0.094 0.495 0.151 0.75 0.161 0.703 0.031 1.161-0.203 1.521-0.682 0.458-0.62 0.109-2.339-0.5-2.563-0.474-0.172-0.755 0.036-1.177 0.068 0.214-0.396 0.464-0.724 0.74-0.958 0.292-0.245 0.604-0.391 0.917-0.396z"/></svg>
      link: https://plurk.com/chyuaner
    # - icon: rss
    #   link: /atom.xml
  components:
    uptime:
      since: "2025/06/09 10:25:33"
      text: "本站建置到現在 已經"
    author:
      homepage: "https://yuaner.tw"
    additional: # 托管信息等
      - - Power by <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a>
        - Source <a href="https://github.com/chyuaner/blog.yuaner.tw" target="_blank">Github Pages</a>

# Post 文章配置
posts:
  default_cover: "/images/default.webp" # 没有头图的文章使用的默认图片
  donate: false # 默认是否启用打赏功能
  share: true # 默认是否启用分享功能
  word_count: # 字数统计功能
    enable: true # 是否启用
    threshold: 1500 # 超过多少字开始显示为千字
    estimate_wavy: true # 在千字的约数前显示波浪号
  toc: # 文章目录
    desktop: # 桌面端
      list_number: false # 显示数字标号
    mobile: # 移动端
      enable: true # 是否启用
      list_number: true # 显示数字标号

# 代码高亮
# syntax_highlighter:
#   theme: atom-dark # 代码高亮主题（请参照具体的高亮插件对应的主题样式）

# Widgets 侧边栏小挂件
sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "分享這篇文章"
  message: ""
  platforms:
    - name: "Facebook"
      icon: <i class="fa-brands fa-facebook-f"></i>
      color: "#4050a0"
      link: "https://www.facebook.com/sharer/sharer.php?u=$URL"
    - name: "Twitter / X"
      icon: <i class="fa-brands fa-twitter"></i>
      color: "#5CA3D4"
      link: "https://x.com/intent/tweet?text=$TITLE&url=$URL"
    - name: "threads"
      icon: <i class="fa-brands fa-threads"></i>
      color: "#000000"
      link: "https://www.threads.net/intent/post?text=$TITLE%20-$SITE%0A%0A$URL"

# 打赏组件设置
donate:
  enable: false
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "https://dev.krt.moe/demo-assets/donate.webp"
  platforms:
    - name: "模拟支付"
      icon: "credit-card"
      color: "skyblue"
      qrcode: "example_payment"

# 版权说明
# copyright_notice:
#   in_page:
#     enable_at:
#       - post
#       - page
#     template: 本作品采用 <a rel="license nofollow" target="_blank" href="https://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a> 进行许可
#   # append_copy: # 在复制时追加
#   #   enable: true # 是否启用
#   #   threshold: 150 # 超过多少字符就追加
#   #   template: | # 模板
#   #     $NEWLINE
#   #     -------------------------
#   #     该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
#   #     作者：$AUTHOR
#   #     来源：$TITLE
#   #     链接：$LINK

# 评论系统
comments:
  core:
    enable_at:
    # - index
      - post
      - page
    template:
      _shared: "<div id='giscus_container' class='kr-comments' data-path='$PATH' data-full-path='$PATH_FULL'></div>"
      index: ""
      post: ""
      page: ""
  count:
    enable_at: 
    # - index
    - post
    template:
      _shared: ""
      index: ""
      post: "<span id='giscus_count'>?</span>"

# 访问数量统计
visit_count:
  enable_at:
      - post
  template:
    _shared: "<span id='page_views_count'>?</span>"
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: |
    <link rel="stylesheet" href="/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="/css/grid.css">
    <link rel="stylesheet" href="/css/spoiler.css">
    <link rel="stylesheet" href="/css/alertbar.css">
  footer: ""
  after_footer: |
    
    <script type="module" src="/comments/giscus.js"></script>
