# https://github.com/Candinya/Kratos-Rebirth/blob/master/_config.yml
################## 系统配置 ##################

search:
  includes:
    - post
    - page

################## 样式配置 ##################
index:
  style: card

# 图片配置
image:
  favicon: "/assets/favicon.png" # 站点图标
  avatar: "https://gravatar.com/avatar/39d6ecc6926e02f7241c8d9225f9eb5a6491a6f13cfaf6ef261b4e44dbd6be55?s=200" # 个人信息挂件上的头像
  banner:
    light: "https://dev.krt.moe/demo-assets/banner.webp"
    dark: "https://dev.krt.moe/demo-assets/banner_dark.webp"
  background:
    light: "https://dev.krt.moe/demo-assets/bg.webp"
    dark: "https://dev.krt.moe/demo-assets/bg.webp"

# 顶部导航栏配置
nav:
  items:
    - label: 首頁
      icon: home
      url: /
    - label: 所有文章
      icon: files-o
      url: /archives/
    # - label: 相關連結
    #   icon: link
    #   submenu:
    #     - label: 代码仓库
    #       icon: code
    #       url: https://github.com/Candinya/Kratos-Rebirth
    #     - label: 项目文档
    #       icon: book
    #       url: https://wiki.krt.moe
    - label: 關於本站
      icon: info-circle
      url: /about/
    - label: RSS
      icon: rss
      url: /atom.xml
    - label: 搜尋
      icon: search
      url: /search/
    - label: 部落格舊站
      icon: clock-o
      url: https://blog-legacy.yuaner.tw

# Footer 页脚配置
footer:
  links:
    - icon: home
      link: https://yuaner.tw
    - icon: github
      link: https://github.com/chyuaner
    - icon: facebook
      link: https://facebook.com/chyuaner
    # - icon: rss
    #   link: /atom.xml
  components:
    uptime:
      since: "2025/06/09 10:25:33"
      text: "本站建置到現在 已經"
    author:
      homepage: "https://yuaner.tw"
    additional: # 托管信息等
      - - Power by <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a>
        - Source <a href="https://github.com/chyuaner/blog.yuaner.tw" target="_blank">Github Pages</a>

# Post 文章配置
posts:
  default_cover: "/images/default.webp" # 没有头图的文章使用的默认图片
  donate: false # 默认是否启用打赏功能
  share: true # 默认是否启用分享功能
  word_count: # 字数统计功能
    enable: true # 是否启用
    threshold: 1500 # 超过多少字开始显示为千字
    estimate_wavy: true # 在千字的约数前显示波浪号
  toc: # 文章目录
    desktop: # 桌面端
      list_number: false # 显示数字标号
    mobile: # 移动端
      enable: true # 是否启用
      list_number: true # 显示数字标号

# 代码高亮
# syntax_highlighter:
#   theme: atom-dark # 代码高亮主题（请参照具体的高亮插件对应的主题样式）

# Widgets 侧边栏小挂件
sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "Facebook"
      icon: <i class="fa fa-facebook"></i>
      color: "#4050a0"
      link: "https://www.facebook.com/sharer/sharer.php?u=$URL"
    - name: "Twitter / X"
      icon: <i class="fa fa-twitter"></i>
      color: "#5CA3D4"
      link: "https://x.com/intent/tweet?text=$TITLE&url=$URL"
    - name: "threads"
      icon: <i class="fa-brands fa-threads"></i>
      color: "#000000"
      link: "https://www.threads.net/intent/post?text=$TITLE%20-$SITE%0A%0A$URL"

# 打赏组件设置
donate:
  enable: false
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "https://dev.krt.moe/demo-assets/donate.webp"
  platforms:
    - name: "模拟支付"
      icon: "credit-card"
      color: "skyblue"
      qrcode: "example_payment"

# 版权说明
# copyright_notice:
#   in_page:
#     enable_at:
#       - post
#       - page
#     template: 本作品采用 <a rel="license nofollow" target="_blank" href="https://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a> 进行许可
#   # append_copy: # 在复制时追加
#   #   enable: true # 是否启用
#   #   threshold: 150 # 超过多少字符就追加
#   #   template: | # 模板
#   #     $NEWLINE
#   #     -------------------------
#   #     该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
#   #     作者：$AUTHOR
#   #     来源：$TITLE
#   #     链接：$LINK

# 评论系统
comments:
  core:
    enable_at:
    # - index
      - post
      - page
    template:
      _shared: "<div id='giscus_container' class='kr-comments' data-path='$PATH' data-full-path='$PATH_FULL'></div>"
      index: ""
      post: ""
      page: ""
  count:
    enable_at: 
    # - index
    - post
    template:
      _shared: ""
      index: ""
      post: "<span id='giscus_count'>?</span>"

# 访问数量统计
visit_count:
  enable_at: []
  template:
    _shared: ""
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: "" # 搜索引擎验证，或是追加的样式表
  footer: ""
  after_footer: |
    <script src="/comments/giscus.js"></script>
